Auth0 tenant can be configured using AUTH0_DOMAIN env var
edgefarm/edgefarm.alm pull request #4
Opened 2021-06-02 12:28 UTC by siredmar

2021-06-07 11:31 UTC, KairaMiu requested changes

2021-06-07 11:31 UTC, KairaMiu commented on service/internal/config/config.go
> +var auth0DomainDefault string = "https://edgefarm.eu.auth0.com"
Use const.

2021-06-07 11:31 UTC, KairaMiu commented on service/internal/config/config.go
> +var auth0DomainDefault string = "https://edgefarm.eu.auth0.com"
Also this is not consistent: 
```
AUTH0_DOMAIN       = test.eu.auth0.com
auth0DomainDefault = https://edgefarm.eu.auth0.com
```

This leads e.g.
```
fmt.Sprintf("https://%s", config.ReadConfig().Auth0Domain)
```
to different results
```
https://test.eu.auth0.com
https://https://edgefarm.eu.auth0.com
```

2021-06-08 05:21 UTC, siredmar commented on service/internal/config/config.go
> +var auth0DomainDefault string = "https://edgefarm.eu.auth0.com"
I'm sorry, this branch is f**cked up. I already fixed those issues in branch `list-deployments`. So Those changes can be reviewed in https://github.com/edgefarm/edgefarm.alm/pull/7.
Closing this PR.

2021-06-08 05:21 UTC, closed without merging